import type { Metadata } from "next";
import { Jost } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
 import "/src/styles/globals.css";

const jost = Jost({ weight: ['300','400', '500','600', '700'],
style: ['normal', 'italic'],
subsets: ['latin'],
display: 'swap', });

export const metadata: Metadata = {
  title: "LLC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jost.className}>{children}</body>
    </html>
  );
}
